name: flutter_cached_svg
description: A high-performance Flutter package for loading and caching SVG images from network URLs with full cross-platform support, including Flutter Web.
version: 1.0.1
homepage: https://github.com/Brughth/flutter_cached_svg
repository: https://github.com/Brughth/flutter_cached_svg
issue_tracker: https://github.com/Brughth/flutter_cached_svg/issues
documentation: https://github.com/Brughth/flutter_cached_svg#readme

# Author and maintainer information
authors:
  - Brughth <brughthsona@gmail.com>

# Environment and compatibility
environment:
  sdk: '>=3.0.0 <4.0.0'
  flutter: '>=3.3.0'

# Main dependencies
dependencies:
  flutter:
    sdk: flutter
  flutter_cache_manager: ^3.4.1
  flutter_svg: ^2.2.0
  http: ^1.4.0

# Development dependencies
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

# Platform support
platforms:
  android:
  ios:
  linux:
  macos:
  web:
  windows:

# Keywords for discoverability on pub.dev
topics:
  - svg
  - cache
  - image
  - web
  - cross-platform

# Screenshots (optional - add if you have images)
# screenshots:
#   - description: 'Basic SVG loading with cache'
#     path: screenshots/basic_usage.png
#   - description: 'Grid of cached SVG images with custom styling'
#     path: screenshots/grid_example.png
#   - description: 'Web compatibility demonstration'
#     path: screenshots/web_demo.png

# Funding/Support (optional)
# funding:
#   - https://github.com/sponsors/Brughth
#   - https://buymeacoffee.com/brughth

# Flutter configuration (cleaned)
flutter:
  # Plugin configuration (if needed in the future)
  # plugin:
  #   platforms:
  #     android:
  #       package: com.example.flutter_cached_svg
  #       pluginClass: FlutterCachedSvgPlugin